Revert "Squashed commit of the following (this time with -X theirs):"
This reverts commit 1c0ea8e0b659bed59eccc98849207dc9bbca4f89.

diff --git a/.github/workflows/build-syncthing.yaml b/.github/workflows/build-syncthing.yaml
--- a/.github/workflows/build-syncthing.yaml
+++ b/.github/workflows/build-syncthing.yaml
@@ -393,18 +393,12 @@ jobs:
             | grep -v /wasm \
           )
 
-          # Build for each platform with errors silenced, because we expect
-          # some oddball platforms to fail. This avoids a bunch of errors in
-          # the GitHub Actions output, instead summarizing each build
-          # failure as a warning.
           for plat in $platforms; do
             goos="${plat%/*}"
             goarch="${plat#*/}"
-            echo "::group ::$plat"
-            if ! go run build.go -goos "$goos" -goarch "$goarch" tar 2>/dev/null; then
-              echo "::warning ::Failed to build for $plat"
+            if ! go run build.go -goos "$goos" -goarch "$goarch" tar ; then
+              echo "*** $plat failed ***"
             fi
-            echo "::endgroup::"
           done
         env:
           CGO_ENABLED: "0"
